version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    command: mix phx.server
    volumes:
      - ".:/app"
      - mix:/mix
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: "healthcheck/postgres:alpine"
    environment:
      POSTGRES_PASSWORD: db_password
volumes:
  mix:
